[versions]
agp = "8.3.0-alpha01"
kotlin = "1.9.0"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.08.00"
appcompat = "1.6.1"
hilt = "2.47"
androidxHiltNavigationCompose = "1.0.0"
coil = "2.2.2"
composeNavigation = "2.7.0"
kotlinxCoroutines = "1.7.1"
ksp = "1.9.0-1.0.11"
moshi = "1.14.0"
retrofit = "2.9.0"
okHttp = "5.0.0-alpha.2"
room = "2.5.2"
coroutinesTest = "1.7.1"
truth = "1.1.3"
mockk = "1.10.0"
turbine = "0.12.1"
mockWebServer = "4.10.0"
testRunner = "1.5.2"
material = "1.9.0"
androidGradlePlugin = "8.1.0"
androidDesugarJdkLibs = "2.0.3"
androidxComposeCompiler = "1.5.1"
jacoco = "0.8.7"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat"}
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}

android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref="lifecycle"}
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref="composeNavigation"}
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
moshi = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
moshi-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okHttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
okHttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest"}
truth = { group = "com.google.truth", name = "truth", version.ref = "truth"}
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk"}
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk"}
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine"}
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockWebServer"}
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt"}
runner = { group = "androidx.test", name = "runner", version.ref = "testRunner"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
